### ISSUE TITLE
Install on Debian 9 error - Command "python setup.py egg_info" failed with error code 1 ...

### ISSUE THREAD

**Issue by Aleksey-Maksimov** [openbacchus/bacchus#16]
Hello

I'm getting an error in step 2 (from https://github.com/openbacchus/bacchus/blob/master/README.md)

```
# apt-get install build-essential (successfully)
# apt-get install libxml2-dev python-dev python-pip libmariadb-dev mariadb-server rabbitmq-server (successfully)
# pip install django==1.10.6 (successfully)
# pip install django-fernet-fields (successfully)
...
# pip install ovirt-engine-sdk-python==4.1.2

Collecting ovirt-engine-sdk-python==4.1.2
  Downloading ovirt-engine-sdk-python-4.1.2.tar.gz (243kB)
    100% |████████████████████████████████| 245kB 1.6MB/s
Requirement already satisfied: enum34 in /usr/lib/python2.7/dist-packages (from ovirt-engine-sdk-python==4.1.2)
Collecting pycurl>=7.19.0 (from ovirt-engine-sdk-python==4.1.2)
  Downloading pycurl-7.43.0.1.tar.gz (195kB)
    100% |████████████████████████████████| 204kB 2.2MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-ZP6Fk5/pycurl/setup.py", line 841, in <module>
        ext = get_extension(sys.argv, split_extension_source=split_extension_source)
      File "/tmp/pip-build-ZP6Fk5/pycurl/setup.py", line 508, in get_extension
        ext_config = ExtensionConfiguration(argv)
      File "/tmp/pip-build-ZP6Fk5/pycurl/setup.py", line 72, in __init__
        self.configure()
      File "/tmp/pip-build-ZP6Fk5/pycurl/setup.py", line 108, in configure_unix
        raise ConfigurationError(msg)
    __main__.ConfigurationError: Could not run curl-config: [Errno 2] No such file or directory

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ZP6Fk5/pycurl/

```
```
# lsb_release -a

No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 9.3 (stretch)
Release:        9.3
Codename:       stretch

```

**Comment by Aleksey-Maksimov** [comment]
Solved by
#apt-get install libcurl4-openssl-dev libssl-dev
