### ISSUE TITLE
Issue when start the backup

### ISSUE THREAD

**Issue by mohammedsaber** [openbacchus/bacchus#18]
hello, i got this error when starting the backup for a vm : 

[root@bacchua ~]# tailf /opt/bacchus/logs/worker.log 
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/celery/app/trace.py", line 367, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/celery/app/trace.py", line 622, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/bacchus/manager/tasks.py", line 24, in backup_vm
    return VMTools.backup_vm(rhevmname,vmname)
  File "/opt/bacchus/manager/vmtools.py", line 216, in backup_vm
    vmbackups.export=export_domain.name
NameError: global name 'vmbackups' is not defined

**Comment by openbacchus** [comment]
Hi,

It was a typo when adding new functionality. I fixed it in the code.

Go to your installation path (default /opt/bacchus ) and run `git pull` command, it will get the fix.

Restart bacchus and try to backup again.
