### ISSUE TITLE
Multiple ovirt clusters

### ISSUE THREAD

**Issue by matonb** [openbacchus/bacchus#9]
I've got a couple of oVirt clusters, which I think is a case you've not covered yet.

Cluster1: `Version 4.1.6.2-1.el7.centos`
Cluster2: `Version 4.1.7.1-1.el7.centos`

I can add manages for each cluster and the vm list reflects machines from both, however I can only backup servers that are in the cluster managed by the first manager entered.

If I try to back up a VM from the second cluster I get the following error in worker.log:

```
[2017-09-26 13:08:39,043: INFO/MainProcess] Received task: manager.tasks.backup_vm[8099b23a-7431-46aa-b0fb-546eb7348f4e]  
[2017-09-26 13:08:39,454: ERROR/ForkPoolWorker-7] Task manager.tasks.backup_vm[8099b23a-7431-46aa-b0fb-546eb7348f4e] raised unexpected: IndexError('list index out of range',)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/celery/app/trace.py", line 367, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/celery/app/trace.py", line 622, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/bacchus/bacchus/manager/tasks.py", line 23, in backup_vm
    return VMTools.backup_vm(rhevmname,vmname)
  File "/home/bacchus/bacchus/manager/vmtools.py", line 183, in backup_vm
    vm = vms_service.list(search='name='+str(vmname))[0]
IndexError: list index out of range
```

I suspect that the backup task is using the first (possibly a random?) manager that it comes across, and not linking / associating virtual machines with specific manager accounts.

**Comment by matonb** [comment]
I just deleted the second oVirt manager, which warned me that all objects under it woiuld be deleted.

All the VM's from the second cluster are still listed in VM Protection -> Virtual Machines

**Comment by bacchus-co** [comment]
Hi,

Multiple managers case is considered. You may see VMTools.backupvm() gets 2 parameters: managername and vmname. 

Can you also share the server.log ?

I have 2 clusters and can run backups on both of them.

Are you running the discovery job periodically ? Can you give some more details ?

**Comment by matonb** [comment]
Which server log are you after ovirt or bacchus ?

I haven't enabled periodic discovery yet.  I keep trying to find time to add a button to the UI to run the task on an ad-hock basis...

**Comment by bacchus-co** [comment]
Sorry I was confused about log.

In worker log it says:

    vm = vms_service.list(search='name='+str(vmname))[0]
IndexError: list index out of range

This means "vms_service.list(search='name='+str(vmname))"   returned an empty list. This could be due to:
 - vm name was changed and periodic discovery is not running
 - vm was deleted and periodic discovery is not running

Could you please enable discovery for this case as explained before ?

**Comment by matonb** [comment]
When I added the 2nd cluster it refreshed the list of all VM's in both clusters.
No VM's were changed or deleted.

I don't want to enable any periodic polling of test software on  my production cluster, I'll park this issue until I enable an alternative solution to polling.

**Comment by matonb** [comment]
I'm still not that happy with it, but I've scheduled the runInventory task.

I've definately only got one oVirt manager listed in the UI, however VM Protection -> Virutal Machines is still listing all VM's from both clusters.

runinventory task has executed a few times now.

Logs:

```
==> beat.log <==
[2017-09-27 17:15:00,448: INFO/MainProcess] Writing entries...
[2017-09-27 17:17:45,340: INFO/MainProcess] Scheduler: Sending due task Discovery (manager.tasks.runInventory)

==> worker.log <==
[2017-09-27 17:17:45,342: INFO/MainProcess] Received task: manager.tasks.runInventory[72e67cc6-daeb-44de-8470-b76099dd2ad8]  
[2017-09-27 17:17:45,345: INFO/ForkPoolWorker-12] manager.tasks.runInventory[72e67cc6-daeb-44de-8470-b76099dd2ad8]: Running Bacchus inventory
[2017-09-27 17:17:45,582: WARNING/ForkPoolWorker-12] <hostname>, already discovered !

< - snip ->

[2017-09-27 17:17:52,365: INFO/ForkPoolWorker-12] Task manager.tasks.runInventory[72e67cc6-daeb-44de-8470-b76099dd2ad8] succeeded in 7.020386672s: True

==> beat.log <==
[2017-09-27 17:18:05,358: INFO/MainProcess] Writing entries...
```

**Comment by bacchus-co** [comment]
I have tested in my environment many times, when a manager is deleted, all objects related to that manager is being deleted. They are relational objects in the database. 

Could it be a browser cache problem ?

**Comment by matonb** [comment]
I don't think so, I've tried on several browsers and even different machines...

**Comment by matonb** [comment]
I just had a look in the database at manager_vm table.

  All vm's had the same cluster_id....

**Comment by bacchus-co** [comment]
closing the issue
